spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://lemur-16.cloud-iam.com/auth/realms/airline}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:https://lemur-16.cloud-iam.com/auth/realms/airline/protocol/openid-connect/certs}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:https://lemur-16.cloud-iam.com/auth}
  realm: ${KEYCLOAK_REALM:airline}
  client-id: ${KEYCLOAK_CLIENT_ID:vinhphucairline-app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:CF1HFGgKedqgmwEVgv1gACiQMyHlRH4y}

eureka:
  client:
    enabled: false

logging:
  level:
    com.skyviet: DEBUG
